[workspace]
members = [
  "winsfs-cli",
  "winsfs-core",
]

[workspace.dependencies]
angsd-saf = "0.1"
rand = "0.8"
rayon = "1"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.test]
opt-level = 3
debug-assertions = true
